# Generated by Django 5.2.1 on 2025-10-15 18:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_days', models.JSONField(default=list, help_text="List of working days (e.g., ['monday', 'tuesday'])")),
                ('start_time', models.TimeField(help_text='Start time of working hours')),
                ('end_time', models.TimeField(help_text='End time of working hours')),
                ('location', models.CharField(blank=True, help_text='Provider location', max_length=200)),
                ('is_accepting', models.BooleanField(default=True, help_text='Whether provider is accepting new bookings')),
                ('description', models.TextField(blank=True, help_text='Provider description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
                'db_table': 'providers',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the service', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the service')),
                ('duration_minutes', models.PositiveIntegerField(default=30, help_text='Duration of the service in minutes')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the service is available')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'services',
                'ordering': ['name'],
            },
        ),
    ]
