# Generated by Django 5.2.1 on 2025-10-15 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='user',
            field=models.OneToOneField(help_text='User account for this provider', on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='provider',
            name='service',
            field=models.ForeignKey(help_text='Service offered by this provider', on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='services.service'),
        ),
    ]
